# Generated by Django 4.2.7 on 2025-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Your response to the customer'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
