# Generated by Django 4.2.7 on 2025-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('amigyrumi', 'Amigurumi'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('home_decor', 'Home Decor'), ('blankets', 'Blankets'), ('toys', 'Toys'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('youtube_link', models.URLField(help_text='YouTube video URL')),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='patterns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
