# Generated by Django 4.2.7 on 2025-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='IMAGE',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pattern',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='category',
            field=models.CharField(choices=[('amigurumi', 'Amigurumi'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('home_decor', 'Home Decor'), ('blankets', 'Blankets'), ('toys', 'Toys'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
