# Generated by Django 4.2.7 on 2025-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_rename_image_pattern_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='pattern',
            name='estimated_time',
            field=models.CharField(blank=True, help_text="e.g., '2-3 hours'", max_length=100),
        ),
        migrations.AddField(
            model_name='pattern',
            name='finished_size',
            field=models.CharField(blank=True, help_text="e.g., '10 inches tall'", max_length=100),
        ),
        migrations.AddField(
            model_name='pattern',
            name='materials',
            field=models.TextField(blank=True, help_text='List of materials needed'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='tutorial_steps',
            field=models.TextField(blank=True, help_text='Step-by-step instructions'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=models.TextField(help_text='Short description (3-5 sentences)'),
        ),
    ]
