# Generated by Django 4.2.7 on 2025-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_pattern_difficulty_pattern_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
